-- File icons
return {
  "nvim-tree/nvim-web-devicons",
  config = function()
    require("nvim-web-devicons").setup({
      override = {
        go = { icon = "", color = "#00ADD8", name = "Go" },
        ["go.mod"] = { icon = "", color = "#00ADD8", name = "GoMod" },
        ["go.sum"] = { icon = "", color = "#00ADD8", name = "GoSum" },
        py = { icon = "", color = "#ffbc03", name = "Python" },
        ts = { icon = "", color = "#3178C6", name = "TypeScript" },
        tsx = { icon = "", color = "#3178C6", name = "TypeScriptReact" },
        js = { icon = "", color = "#F7DF1E", name = "JavaScript" },
        jsx = { icon = "", color = "#61DAFB", name = "JavaScriptReact" },
        cpp = { icon = "", color = "#519aba", name = "Cpp" },
        c = { icon = "", color = "#599eff", name = "C" },
        h = { icon = "", color = "#a074c4", name = "Header" },
        hpp = { icon = "", color = "#a074c4", name = "HppHeader" },
        lua = { icon = "", color = "#51a0cf", name = "Lua" },
        rs = { icon = "", color = "#dea584", name = "Rust" },
        toml = { icon = "", color = "#9c4221", name = "Toml" },
        json = { icon = "", color = "#cbcb41", name = "Json" },
        yaml = { icon = "", color = "#6d8086", name = "Yaml" },
        yml = { icon = "", color = "#6d8086", name = "Yml" },
        md = { icon = "", color = "#519aba", name = "Markdown" },
        html = { icon = "", color = "#e34c26", name = "Html" },
        css = { icon = "", color = "#563d7c", name = "Css" },
        scss = { icon = "", color = "#cc6699", name = "Scss" },
        sh = { icon = "", color = "#4d5a5e", name = "Shell" },
        bash = { icon = "", color = "#4d5a5e", name = "Bash" },
        zsh = { icon = "", color = "#4d5a5e", name = "Zsh" },
        vim = { icon = "", color = "#019833", name = "Vim" },
        git = { icon = "", color = "#F14C28", name = "Git" },
        gitignore = { icon = "", color = "#F14C28", name = "GitIgnore" },
        dockerfile = { icon = "", color = "#384d54", name = "Dockerfile" },
        docker = { icon = "", color = "#384d54", name = "Docker" },
        sql = { icon = "", color = "#dad8d8", name = "Sql" },
        graphql = { icon = "", color = "#e535ab", name = "GraphQL" },
        env = { icon = "", color = "#faf743", name = "Env" },
        lock = { icon = "", color = "#bbbbbb", name = "Lock" },
        makefile = { icon = "", color = "#6d8086", name = "Makefile" },
        license = { icon = "", color = "#d0bf41", name = "License" },
        txt = { icon = "", color = "#89e051", name = "Text" },
        conf = { icon = "", color = "#6d8086", name = "Conf" },
        cfg = { icon = "", color = "#6d8086", name = "Cfg" },
      },
      override_by_filename = {
        [".gitignore"] = { icon = "", color = "#F14C28", name = "GitIgnore" },
        [".gitattributes"] = { icon = "", color = "#F14C28", name = "GitAttributes" },
        [".env"] = { icon = "", color = "#faf743", name = "Env" },
        [".env.local"] = { icon = "", color = "#faf743", name = "EnvLocal" },
        [".env.example"] = { icon = "", color = "#faf743", name = "EnvExample" },
        ["docker-compose.yml"] = { icon = "", color = "#384d54", name = "DockerCompose" },
        ["docker-compose.yaml"] = { icon = "", color = "#384d54", name = "DockerCompose" },
        ["Makefile"] = { icon = "", color = "#6d8086", name = "Makefile" },
        ["CMakeLists.txt"] = { icon = "", color = "#6d8086", name = "CMake" },
        ["README.md"] = { icon = "", color = "#519aba", name = "Readme" },
        ["package.json"] = { icon = "", color = "#e8274b", name = "PackageJson" },
        ["tsconfig.json"] = { icon = "", color = "#3178C6", name = "TSConfig" },
        [".prettierrc"] = { icon = "", color = "#cbcb41", name = "Prettier" },
        [".eslintrc.js"] = { icon = "", color = "#4b32c3", name = "Eslint" },
      },
      default = true,
      strict = true,
      color_icons = true,
    })
  end,
}
